<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Orba\MicroFeatures\ViewModel\Customer\Address\Form\InputMask $viewModel */
$viewModel = $block->getData('view_model');
$telephoneInputMask = $viewModel->getTelephoneInputMask();
$postcodeInputMask = $viewModel->getPostcodeInputMask();
?>
<?php if ($telephoneInputMask): ?>
<script type="text/x-magento-init">
{
    "#telephone": {
        "orba/inputMask": {"mask": "<?= $escaper->escapeJs($telephoneInputMask) ?>"},
        "orba/validationAdder": {"validate": {"orba-input-mask-complete": true}}
    }
}
</script>
<?php endif ?>
<?php if ($postcodeInputMask): ?>
<script type="text/x-magento-init">
{
    "#zip": {
        "orba/inputMask": {"mask": "<?= $escaper->escapeJs($postcodeInputMask) ?>"},
        "orba/validationAdder": {"validate": {"orba-input-mask-complete": true}}
    }
}
</script>
<?php endif ?>
