<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Lingaro\MicroFeatures\ViewModel\Customer\Address\Form\InputMask $viewModel */
$viewModel = $block->getData('view_model');
$telephoneInputMask = $viewModel->getTelephoneInputMask();
$postcodeInputMask = $viewModel->getPostcodeInputMask();
?>
<?php if ($telephoneInputMask): ?>
<script type="text/x-magento-init">
{
    "#telephone": {
        "lingaro/inputMask": {"mask": "<?= $escaper->escapeJs($telephoneInputMask) ?>"},
        "lingaro/validationAdder": {"validate": {"lingaro-input-mask-complete": true}}
    }
}
</script>
<?php endif ?>
<?php if ($postcodeInputMask): ?>
<script type="text/x-magento-init">
{
    "#zip": {
        "lingaro/inputMask": {"mask": "<?= $escaper->escapeJs($postcodeInputMask) ?>"},
        "lingaro/validationAdder": {"validate": {"lingaro-input-mask-complete": true}}
    }
}
</script>
<?php endif ?>
