<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Lingaro\MicroFeatures\ViewModel\UpsertQtyInitializer $viewModel */
$viewModel = $block->getViewModel();
$viewModel->setProduct($block->getProduct());
?>
<?php if ($viewModel->isEnabled() && $viewModel->getProduct()->isSaleable()): ?>
    <?php $targetSelector = '#product_addtocart_form'; ?>
<div data-mage-init='<?= $escaper->escapeHtmlAttr($viewModel->getJsonConfig($targetSelector)) ?>'></div>
<style>
    <?= /* @noEscape */ $targetSelector ?> {
        display: none;
    }
</style>
<?php endif; ?>
