<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="text/x-magento-init">
     {
         "#newsletter-validate-detail": {
             "Lingaro_MicroFeatures/js/newsletter/ajax": {}
         }
     }
</script>
