<?php

/**
 * @copyright Copyright © 2022 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="text/x-magento-init">
     {
         "#newsletter-validate-detail": {
             "Orba_MicroFeatures/js/newsletter/ajax": {}
         }
     }
</script>
